export const platformGroups = [
  "All",
  "Media activation",
  "Retail & audience",
  "AI & automation",
  "Measurement & operations",
];
const p = (id, name, group, mark, color, status, description) => ({
  id,
  name,
  group,
  mark,
  color,
  status,
  description,
});
export const platforms = [
  p(
    "dv360",
    "DV360",
    "Media activation",
    "DV",
    "#6dcc89",
    "Hands-on",
    "Campaign trafficking, pacing, bid and frequency diagnostics, audience targeting, and creative-rejection troubleshooting.",
  ),
  p(
    "ttd",
    "The Trade Desk",
    "Media activation",
    "ttd",
    "#5bb9f3",
    "Hands-on · Kokai certified",
    "Offsite programmatic campaign delivery, optimization, and placement reporting. Trading Essentials: Kokai certified in June 2026.",
  ),
  p(
    "gam",
    "Google Ad Manager",
    "Media activation",
    "GAM",
    "#56c0b0",
    "Hands-on",
    "Onsite native delivery, targeting configuration, pacing, pricing and campaign setup QA.",
  ),
  p(
    "meta",
    "Meta Ads",
    "Media activation",
    "∞",
    "#7ab9fa",
    "Hands-on",
    "Paid social execution, Advantage+ campaigns, budget checks, creative testing and performance optimization.",
  ),
  p(
    "pinterest",
    "Pinterest Ads",
    "Media activation",
    "P",
    "#fa9d9d",
    "Hands-on",
    "Retail media campaign activation, pacing and cross-platform delivery monitoring.",
  ),
  p(
    "googleads",
    "Google Ads",
    "Media activation",
    "Ads",
    "#ebd17c",
    "Hands-on",
    "Paid search and performance campaigns, including Performance Max as part of the Solva skincare channel mix.",
  ),
  p(
    "tiktok",
    "TikTok",
    "Media activation",
    "tk",
    "#7fd6d3",
    "Pacing & QA",
    "Cross-platform pacing and delivery monitoring, supported by the Microsoft 365 evidence review.",
  ),
  p(
    "youtube",
    "YouTube / TrueView",
    "Media activation",
    "▶",
    "#f6999e",
    "Earlier hands-on",
    "YouTube Masthead booking, pacing and reporting for Snowflake Summit 2022. Earlier TrueView experience.",
  ),
  p(
    "cm360",
    "Campaign Manager 360",
    "Media activation",
    "CM",
    "#9bb6f2",
    "Earlier hands-on",
    "Prior campaign management experience. Presented as earlier experience rather than a recent operating platform.",
  ),
  p(
    "amazon",
    "Amazon DSP",
    "Media activation",
    "a",
    "#f4bc78",
    "Certified",
    "Amazon DSP certified, valid through August 2027. Part of my continuing development in retail media.",
  ),
  p(
    "gmp",
    "Google Marketing Platform",
    "Media activation",
    "GMP",
    "#88b7ef",
    "Platform ecosystem",
    "The Google advertising ecosystem connecting the DV360, Google Ad Manager and earlier CM360 work represented here.",
  ),
  p(
    "pentaleap",
    "Pentaleap",
    "Retail & audience",
    "PL",
    "#b4cbf5",
    "Hands-on",
    "Sponsored-product campaign setup, keywords, budgets, optimization and UPC-list management.",
  ),
  p(
    "liveramp",
    "LiveRamp",
    "Retail & audience",
    "LR",
    "#b9a5f5",
    "Hands-on",
    "Retail audience segmentation to support advertiser targeting and activation.",
  ),
  p(
    "liveintent",
    "LiveIntent",
    "Retail & audience",
    "LI",
    "#e5c27b",
    "Hands-on",
    "Email and offer activity within retail media workflows.",
  ),
  p(
    "aistudio",
    "Google AI Studio",
    "AI & automation",
    "AI",
    "#adcaf5",
    "Independent AI toolkit",
    "Exploring and applying AI to ad-tech learning and workflow ideas, alongside the independent ProgrammaticOS initiative.",
  ),
  p(
    "copilot",
    "Copilot Studio",
    "AI & automation",
    "Co",
    "#bea7f2",
    "Beta prototype",
    "Personally beta-testing advertiser-specific trafficking-sheet guidance using SharePoint knowledge across a 100+ advertiser environment.",
  ),
  p(
    "adreform",
    "AdReform",
    "AI & automation",
    "AR",
    "#b5f493",
    "Workflow integration",
    "Designed API-integrated screenshot workflows for onsite native and offsite DV360 / The Trade Desk placements, freeing at least 10 hours weekly.",
  ),
  p(
    "sharepoint",
    "SharePoint",
    "AI & automation",
    "SP",
    "#71c6bc",
    "Knowledge source",
    "Information uploaded to SharePoint supports the Copilot Studio trafficking-sheet prototype.",
  ),
  p(
    "api",
    "API workflows",
    "AI & automation",
    "API",
    "#92d8b2",
    "Workflow integration",
    "Connecting existing services to automate placement-specific screenshot and reporting tasks.",
  ),
  p(
    "jira",
    "Jira",
    "Measurement & operations",
    "J",
    "#8eaff5",
    "Hands-on",
    "Campaign issue escalation, technical follow-through and operational coordination.",
  ),
  p(
    "excel",
    "Microsoft Excel",
    "Measurement & operations",
    "XL",
    "#7ccbae",
    "Operational toolkit",
    "Pacing logs, reporting workflows, campaign checks and operational analysis.",
  ),
  p(
    "powerpoint",
    "PowerPoint",
    "Measurement & operations",
    "PP",
    "#e0a08d",
    "Operational toolkit",
    "Proof-of-performance decks and clear stakeholder reporting.",
  ),
  p(
    "advendio",
    "Advendio",
    "Measurement & operations",
    "AD",
    "#9fbeef",
    "Operational toolkit",
    "Ad-operations tooling within the broader campaign-management toolkit.",
  ),
  p(
    "ias",
    "Integral Ad Science",
    "Measurement & operations",
    "IAS",
    "#9fd7c0",
    "Operational toolkit",
    "Ad-verification tooling within the broader media-quality toolkit.",
  ),
  p(
    "ga4",
    "Google Analytics 4",
    "Measurement & operations",
    "GA4",
    "#f3c478",
    "Hands-on",
    "Experience with GA4 for advertising measurement and reporting.",
  ),
  p(
    "floodlight",
    "Floodlight",
    "Measurement & operations",
    "FL",
    "#c8b597",
    "Tracking toolkit",
    "Conversion-tracking technology within the Google advertising ecosystem.",
  ),
  p(
    "gtm",
    "Google Tag Manager",
    "Measurement & operations",
    "GTM",
    "#94baf4",
    "Hands-on",
    "Experience with GTM for tag management and measurement setup.",
  ),
  p(
    "looker",
    "Looker Studio",
    "Measurement & operations",
    "LS",
    "#aab9fa",
    "Hands-on",
    "Experience with Looker Studio for reporting and data visualization.",
  ),
  p(
    "salesforce",
    "Salesforce",
    "Measurement & operations",
    "SF",
    "#9bd1f5",
    "Wider toolkit",
    "CRM tooling in the wider operations toolkit.",
  ),
];
export const companies = [
  {
    id: "dentsu",
    name: "Dentsu",
    period: "Dec 2023 – Present",
    role: "Account Services Manager · Programmatic",
    summary:
      "100–130+ retail media campaigns. Precision, problem-solving, and smarter workflows.",
    color: "#b5f493",
    badge: "Promoted · Jul 2026",
    intro:
      "Keeping a complex retail media ecosystem moving, with hands-on campaign execution and technical judgment.",
    progression: [
      ["Dec 2023 – Jun 2026", "Account Manager"],
      ["Jul 2026 – Present", "Account Services Manager"],
    ],
    metrics: [
      ["98%+", "delivery in full"],
      ["619,636", "impressions recovered"],
      ["10+ hrs", "freed each week"],
    ],
    responsibilities: [
      "Daily pacing, QA and optimization across GAM, DV360, The Trade Desk, Meta, Pinterest and Pentaleap.",
      "Pentaleap setup, keywords, budgets and UPC lists; LiveRamp audience segmentation and LiveIntent activity.",
      "Campaign coordination with US activation teams, advertiser discussions, audience forecasting and Jira escalations.",
      "Beta-testing a SharePoint-backed Copilot Studio prototype for advertiser-specific trafficking sheets.",
    ],
    outcomes: [
      "Designed API-integrated AdReform placement-screenshot workflows, freeing at least 10 hours of manual work weekly.",
      "Identified multi-flight underdelivery and coordinated allocation to the active flight, recovering 619,636 impressions.",
      "Diagnosed a crawl-access issue affecting DV360 creatives across 50+ advertisers; client developers implemented the recommendations.",
      "Owned the optimization portion of the retail media delivery tracker from March 2025, before the July 2026 promotion.",
    ],
    recognition: [
      ["2026", "Make It Real Award"],
      ["2025", "Climb High Award"],
    ],
    tools: [
      "GAM",
      "DV360",
      "The Trade Desk",
      "Meta",
      "Pinterest",
      "Pentaleap",
      "LiveRamp",
      "LiveIntent",
      "AdReform",
      "Jira",
    ],
    note: "The AdReform saving and the Copilot beta prototype are separate initiatives.",
  },
  {
    id: "freyr",
    name: "Freyr Solutions",
    period: "Apr 2023 – Oct 2023",
    role: "Paid & Programmatic Specialist",
    summary:
      "A stronger channel mix for Solva skincare. Blended ROAS of 4.8 by month six.",
    color: "#96befe",
    intro:
      "Connecting paid social, search and programmatic awareness to a retail growth challenge.",
    metrics: [
      ["0.78 → 1.2", "ROAS, first month"],
      ["4.8", "blended ROAS, month six"],
      ["₹1M", "monthly media budget"],
    ],
    responsibilities: [
      "Managed campaigns across Meta, Google and DV360 for Solva skincare.",
      "Used Meta Advantage+, seasonal promotions and customized landing pages to improve early performance.",
      "Introduced DV360 in month two alongside Meta Advantage+ and Google Performance Max.",
    ],
    outcomes: [
      "Raised ROAS from approximately 0.78 to 1.2 in the first month.",
      "Achieved blended ROAS of 4.8 by month six, including awareness spend.",
      "Supported sell-through of inventory valued above INR 100 million and recovery of prior losses attributable to Solva.",
    ],
    tools: [
      "Meta Advantage+",
      "Google Performance Max",
      "DV360",
      "Landing pages",
    ],
    chart: true,
    note: "ROAS figures describe different stages. The 4.8 result is a month-six endpoint, not a six-month average.",
  },
  {
    id: "otsi",
    name: "OTSI",
    period: "Dec 2021 – Apr 2023",
    role: "Digital Marketing & Programmatic Specialist",
    summary:
      "From paid search and social into programmatic. 150K+ people reached for Snowflake Summit.",
    color: "#c7b0fb",
    intro:
      "Turning an event-marketing brief into coordinated reach, registration and sales support.",
    metrics: [
      ["150K+", "unique people reached"],
      ["500+", "registrations supported"],
      ["5", "booth sales by sales team"],
    ],
    responsibilities: [
      "Managed YouTube Masthead booking, pacing and reporting for Snowflake Summit 2022; advised the creative team.",
      "Coordinated DV360 reseller access, campaign setup and audiences to expand the channel mix.",
      "Supported promotion as a Summit partner and sponsor focused on banking and software sectors.",
    ],
    outcomes: [
      "Reached more than 150,000 unique people through the YouTube Masthead campaign.",
      "Contributed to more than 500 registrations.",
      "Generated leads that the sales team converted into five booth sales.",
    ],
    tools: ["YouTube Masthead", "DV360", "Google Ads", "Meta Ads"],
    note: "Registrations were a shared contribution; booth-sale conversions were completed by the sales team.",
  },
  {
    id: "shiftwave",
    name: "Shiftwave Technologies",
    period: "Jul 2018 – Jul 2021",
    role: "Digital Marketing Manager",
    summary:
      "Led a 10-person team across search, paid media, social and content.",
    color: "#efc18d",
    intro:
      "A leadership foundation built through client strategy, execution and developing a multidisciplinary team.",
    metrics: [
      ["10", "direct reports"],
      ["45%", "Express Flooring sales lift"],
      ["35%+", "Bodcor sales lift"],
    ],
    responsibilities: [
      "Assigned work, trained colleagues and reviewed deliverables across SEO, paid advertising, social media and content.",
      "Gathered client requirements and developed marketing strategies through client calls and team planning.",
      "Improved landing pages, video reviews, targeting, search terms and website content.",
    ],
    outcomes: [
      "Helped increase Express Flooring sales by 45% and Bodcor sales by more than 35% over eight months.",
      "Improved core business keyword rankings and time on site through SEO and content improvements.",
    ],
    tools: [
      "SEO",
      "Google Ads",
      "Meta Ads",
      "Content strategy",
      "Landing pages",
    ],
    note: "Sales outcomes were contributed to through team execution; they are not represented as sole attribution.",
  },
  {
    id: "freelance",
    name: "Independent consulting",
    period: "Sep 2017 – Jul 2018",
    role: "Freelance Digital Marketing Consultant",
    summary: "Content, SEO and paid advertising for multiple clients.",
    color: "#b5c9cf",
    intro:
      "Learning the business from the ground up, through hands-on work for multiple clients.",
    responsibilities: [
      "Delivered content creation, SEO and paid advertising services for multiple clients.",
    ],
    outcomes: [],
    tools: ["Content", "SEO", "Paid advertising"],
  },
  {
    id: "myvash-history",
    name: "Myvash.com",
    period: "Aug 2015 – Sep 2017",
    role: "Founder · Technology blog",
    summary:
      "The original independent build: publishing, SEO, distribution and monetization.",
    color: "#b5f493",
    intro:
      "An early entrepreneurial chapter that combined technology publishing with audience growth.",
    metrics: [["~120K", "global Alexa rank in 2015"]],
    responsibilities: [
      "Founded and operated a technology blog.",
      "Managed website setup, writing, SEO, social promotion and monetization.",
    ],
    outcomes: ["Reached approximately 120,000 in global Alexa rank in 2015."],
    tools: ["Publishing", "SEO", "Social promotion"],
    note: "This is the original 2015–2017 technology blog, distinct from the current Myvash consultancy initiative.",
  },
];
export const caseStudies = [
  {
    id: "reporting",
    name: "From repetitive screenshots to a connected workflow.",
    type: "AUTOMATION / DENTSU",
    metric: "10+ hrs",
    unit: "manual work freed weekly",
    intro:
      "The opportunity was not another dashboard. It was removing repetitive work from the reporting process.",
    steps: [
      "Placement inputs",
      "API submission",
      "AdReform capture",
      "Reporting QA",
    ],
    situation:
      "Onsite native and offsite placements required repeated, placement-specific screenshots and validation.",
    contribution:
      "Designed API-integrated AdReform workflows for onsite search/category placements and offsite DV360 / The Trade Desk activity. Kept placement checks and manual fallbacks in the workflow.",
    outcome:
      "Freed at least 10 hours of manual work each week, giving the team more time for campaign delivery and optimization.",
    tools: ["AdReform", "API workflows", "DV360", "The Trade Desk"],
    note: "Workflow illustration. It does not run against advertising accounts.",
  },
  {
    id: "diagnosis",
    name: "Following a creative rejection back to its source.",
    type: "TECHNICAL DIAGNOSIS / DENTSU",
    metric: "50+",
    unit: "advertisers affected",
    intro:
      "When the visible symptom was in the ad platform, the underlying issue was on the destination website.",
    steps: [
      "Rejected creative",
      "URL analysis",
      "Crawl-access finding",
      "Developer handoff",
    ],
    situation:
      "DV360 destination crawl-access rejections affected advertisers within a retail media network.",
    contribution:
      "Investigated landing-page patterns and robots.txt access, documented the diagnosis, and provided actionable remediation recommendations for onshore stakeholders and client developers.",
    outcome:
      "Google support corroborated the blocked-path assessment. Client developers implemented the recommendations to address an issue affecting more than 50 advertisers.",
    tools: ["DV360", "Landing-page QA", "Issue tracking"],
    note: "Diagnosis and recommendations were my contribution. Website deployment belonged to the client’s developers.",
  },
  {
    id: "recovery",
    name: "Finding the impressions between campaign flights.",
    type: "PACING & RECONCILIATION / DENTSU",
    metric: "619,636",
    unit: "missed impressions recovered",
    intro:
      "Looking beyond the active flight revealed the gap that a single pacing snapshot could miss.",
    steps: [
      "Flight review",
      "Plan reconciliation",
      "Allocation handoff",
      "Delivery follow-through",
    ],
    situation:
      "An underdelivery issue spanned multiple campaign flights, requiring reconciliation rather than an isolated bid adjustment.",
    contribution:
      "Reviewed earlier-flight delivery against the media plan, identified the missing impressions and coordinated their allocation to the active flight with the activation team.",
    outcome:
      "Recovered 619,636 missed impressions through flight reconciliation, allocation planning and activation-team follow-through.",
    tools: ["DV360", "Pacing logs", "Cross-team coordination"],
    note: "A delivery recovery built on careful analysis and cross-team coordination.",
  },
];
export const credentials = [
  ["Google", "Display & Video 360", "Valid through May 2027"],
  ["The Trade Desk", "Trading Essentials: Kokai", "Issued June 2026"],
  ["Amazon", "Amazon DSP", "Valid through August 2027"],
  ["Google", "AI Professional Certificate", "Issued June 2026"],
  ["The Trade Desk", "Marketing Essentials", "Issued June 2026"],
  ["Google", "AI Powered Performance Ads", "Valid through November 2026"],
];
